export const fruitIcons = [
    { icon: "milho" },
    { icon: "apple" },
    { icon: "melancia" },
    { icon: "banana" },
    { icon: "tomate" },
    { icon: "watering"},
    { icon: "cenoura"},
    { icon: "trator"},
    { icon: "trator2"},
    { icon: "coconut1"},
    { icon: "coconut2"},
    { icon: "chuva"},
    { icon: "shears"},
    { icon: "barn"},
    { icon: "cacao"},
    { icon: "agricultor"},
    { icon: "agricultor2"},
  ];